use_frameworks!

platform :ios, '8.0'

target 'MGZPersonPrefrenceCategoryKit_Example' do
  pod 'MGZPersonPrefrenceCategoryKit', :path => '../'

  target 'MGZPersonPrefrenceCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
